"""Concrete Pixel Lab requests for ASSET_MANIFEST.md; no network calls."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LIB=ROOT/'art_library'
STYLE='Original dark fantasy pixel art for a ruined magical academy RPG. Crisp pixel clusters, limited desaturated blue gray stone and weathered bronze palette, upper-left lighting, thin dark outline, readable at native resolution. No text, no letters, no watermark. '
queue=[]
def add(id,endpoint,payload,**kw):queue.append(dict(id=id,endpoint=endpoint,payload=payload,**kw))
def still(id,description,size=64,view='low top-down',transparent=True,**kw):
 add(id,'/create-image-pixen',dict(description=STYLE+description,image_size=dict(width=size,height=size),no_background=transparent,view=view,outline='single color black outline',detail='medium detail'),**kw)
def anim(id,parent,action,frames=8):
 add(id,'/animate-with-text-v3',dict(action=action,frame_count=frames,no_background=True),first_frame=parent,depends=[parent])
directions=['south','south-east','east','north-east','north','north-west','west','south-west']
hero=json.loads((LIB/'requests/CH-01.json').read_text())
add('CH-01','/create-character-v3',hero)
characters=[
 ('CH-01',None,8,['move','idle','cast','channel','dodge','hurt','death']),
 ('EN-01','Ruin Skitter, an unsettling small hunched bipedal arcane vermin with long claws and a ragged silhouette, dusty charcoal skin, small amber eyes',4,['idle','move','attack','hurt','death']),
 ('EN-02','Ashbound Scholar, undead academy scholar in ragged gray violet robes and cracked ceremonial mask, holding a dim ember focus',4,['idle','move','cast','hurt','death']),
 ('EN-03','Broken Sentinel, bulky animated empty stone and bronze academy armor, broad shoulders, fractured chest rune, heavy fists',4,['idle','move','attack','hurt','death']),
 ('BO-01','Corrupted Warden, imposing former wizard headmaster, tall dark robes with bronze ward armor, split ceremonial crown and corrupted violet crystal staff, readable regal silhouette',4,['idle','move','attack','cast','summon','stagger','death']),
 ('NPC-01','Academy caretaker, elderly human in faded brown and teal robes, ring of keys at belt, kind weary face, walking cane',4,['idle']),
 ('NPC-02','Rescued artificer, adult human artisan, leather apron over moss gray clothes, small brass tools on belt, practical short hair',4,['idle'])]
actions={'move':'Seamless walking cycle in place, feet alternately stepping, natural robe sway, staff held consistently, fixed camera, no translation, no effects.','idle':'Subtle seamless breathing idle loop in place, preserve pose and staff, no effects.','cast':'Raise staff and extend free hand to cast a spell, readable anticipation and recovery, no added spell effects.','channel':'Hold staff forward and sustain a spell, subtle looping robe motion, planted feet, no added spell effects.','dodge':'Quick evasive side step with low crouch, return to standing, no camera motion.','hurt':'Brief recoil from being hit, then recover to original pose.','death':'Collapse to the ground and remain motionless at the end.','attack':'Readable windup followed by one forward strike and recovery.','summon':'Lift staff high and spread free hand in a dramatic summoning gesture, then recover.','stagger':'Lose balance and stagger backward, then regain posture.'}
# Wizard walk/idle tasks precede all other artwork for the minimal prototype.
for cid,desc,count,moves in characters:
 if desc:
  size=96 if cid=='BO-01' else 64
  add(cid,'/create-character-v3',dict(name=cid+' '+desc.split(',')[0],description=STYLE+desc+'. Full body standing, centered, visible feet, transparent background, no scenery.',image_size=dict(width=size,height=size),view='low top-down',no_background=True,outline='single color black outline',detail='medium detail'))
 for action in moves:
  for direction in (directions if count==8 else ['south','east','north','west']):
   add(cid+'-'+action+'-'+direction,'/animate-character',dict(animation_name=action,action_description=actions[action],mode='v3',frame_count=8 if action=='move' else 4,keep_first_frame=False,directions=[direction]),character=cid,depends=[cid])
# Portraits retain the established written character design.
for cid,desc in [('CH-01','young former student wizard with midnight blue hood, teal lining, bronze clasp, resolute face'),('NPC-01','elderly academy caretaker in brown and teal, kind weary face'),('NPC-02','practical short-haired adult artificer wearing a leather apron')]:
 still(cid+'-portrait','Head and shoulders portrait of '+desc+', centered.',96,view='side')
terrain=[('ENV-01-grass-earth','dead desaturated grass','dark compact earth','sparse dry grass meeting bare earth'),('ENV-01-earth-stone','dark compact earth','weathered gray academy flagstone','worn stone edges at dirt'),('ENV-01-cracked-stone','intact gray academy flagstone','cracked gray academy flagstone','subtle cracked stone boundary'),('ENV-01-corruption','weathered gray academy flagstone','dark violet corrupted flagstone','creeping dark violet fissures'),('ENV-02-floor','intact blue gray academy interior floor','damaged blue gray academy floor','subtle chipped edges'),('ENV-02-ritual','blue gray academy floor','faint circular arcane ritual floor motifs, no lettering','subtle inlaid bronze patterns'),('ENV-02-pit','pitch dark empty pit','blue gray academy stone floor','clear stone ledge'),('ENV-02-corruption','blue gray academy interior floor','violet corrupted interior floor','thin spreading violet cracks')]
for id,lo,hi,tr in terrain:
 add(id,'/create-tileset',dict(lower_description=STYLE+lo,upper_description=STYLE+hi,transition_description=tr,tile_size=dict(width=32,height=32),transition_size=0,view='low top-down',mode='standard',detail='medium detail',shading='medium shading'),reserve=20)
architecture=['straight horizontal wall','straight vertical wall','inner wall corner','outer wall corner','wall end cap','front facing wall face','archway','open doorway threshold','short stairs ascending north','short stairs ascending east','intact stone pillar','ruined wall segment','ruined workshop facade overlay','restored workshop facade overlay']
for i,name in enumerate(architecture,1):still('ENV-03-'+str(i).zfill(2),'Single modular '+name+' made of weathered academy blue gray stone and bronze, orthogonal floor grid, isolated transparent background.',128 if 'facade' in name else 64)
props=['small rubble','large rubble','broken column','fallen statue','dead tree','root cluster','torn academy banner','broken desk','bookshelf','book pile','lectern','desk','chair','chalkboard without writing','alchemy table','ritual pedestal','closed chest','closed door','closed academy gate','dormant ward beacon','ruined workbench','stash trunk','available withered herb gathering node','available aether crystal gathering node','candle stand','brazier','bench','rug','planter','crate','freestanding banner','stone ornament']
for i,name in enumerate(props,1):still('PROP-'+str(i).zfill(2),'One '+name+', isolated game prop, centered with transparent background.',64)
for id,name in [('17','open chest'),('18','open door'),('19','open academy gate'),('20','active ward beacon'),('21','restored workbench'),('23','depleted herb gathering node'),('24','depleted crystal gathering node')]:still('PROP-'+id+'-state','One '+name+', weathered stone wood and bronze academy prop, centered transparent background.',64)
for id,action in [('PROP-25','Small candle flame flickering gently, all solid parts stationary.'),('PROP-26','Brazier embers and flame flickering, fixed metal body.'),('PROP-20-state','Soft cyan ward light pulsing, stone body stationary.')]:anim(id+'-ambient',id,action,4)
fx=[('Firebolt projectile','compact orange fireball pointing east with a short flame tail','Flame tail flickers in a seamless loop, projectile stays centered.'),('Fire impact','small orange starburst magical fire impact','Burst expands and dissipates to transparency.'),('Burning','small vertical orange flame status effect','Looping flickering small flames.'),('Frost Nova','cyan ice nova ring viewed from an elevated top-down camera','Ring expands outward with sharp ice shards and fades.'),('Chilled status','small pale blue frost crystal cluster around an empty center','Subtle ice shimmer loop.'),('Soul Drain','short horizontal crimson violet magical energy tether segment','Energy travels along the tether, seamless loop.'),('Blood payment','compact dark red magical pulse with an empty center','Brief inward pulse then fade.'),('Life return','small crimson and pale cyan life energy motes','Particles move inward to the center and vanish.'),('Dodge trail','small gray dust puff trail','Dust expands briefly and fades.'),('Physical hit','small pale gold impact spark with stone debris','Quick spark burst and fade.'),('Enemy magic','small hostile violet projectile with short tail','Violet flame trail loops.'),('Warden hazard','compact violet arcane ground eruption','Ground energy erupts upward and dissipates.'),('Warden summon','violet circular summoning ring without lettering','Ring pulses and wisps rise then fade.'),('Loot pickup','small warm gold four pointed glint','Bright brief sparkle then fade.'),('Level up','small pale gold and cyan celebratory ring','Ring expands upward with a few light motes then fades.'),('Ward activation','pale cyan circular ward energy ring','Gentle outward energy pulse then fade.')]
for i,(name,desc,action) in enumerate(fx,1):
 id='FX-'+str(i).zfill(2)
 still(id,desc+', isolated effect only, no character, no terrain, transparent background.',96 if i in [4,12,13,15,16] else 64)
 anim(id+'-animation',id,action,8)
# Extra pieces needed by multi-component effect families.
for id,desc in [('FX-06-contact','small crimson violet energy contact spark'),('FX-11-impact','small violet hostile spell impact spark')]:
 still(id,desc+', isolated on transparent background.',64)
 anim(id+'-animation',id,'Brief magical impact burst that expands and fades.',4)
icons=['apprentice staff','ember staff','rime staff','bloodwood staff','student robe','warded robe','ashweave robe','ritual vestment','copper focus ring','quartz seal ring','frost band ring','sanguine loop ring','Firebolt spell','Frost Nova spell','Soul Drain spell','split projectile modifier','piercing projectile modifier','wider nova modifier','lingering frost modifier','longer drain modifier','empowered drain modifier','fire passive','frost passive','lightning passive','blood passive','curse passive','necromancy passive','spell power passive','critical chance passive','cast speed passive','health passive','mana passive','defense passive','withered herb','aether crystal','restorative draught','refined aether focus','academy seal quest item','recovered journal quest item','warden fragment quest item']
for i,name in enumerate(icons,1):still('ICON-'+str(i).zfill(2),'One inventory or skill icon depicting '+name+', bold readable shape, centered, no border, no lettering.',32,view='side')
ui=['health and mana bar frame with separate red and blue fill strips','square skill slot frame with selected and neutral variants','square inventory equipment slot frame with neutral hover and equipped variants','item tooltip dark panel with bronze border and small rarity accent swatches','dialogue dark panel with portrait frame','small quest tracker backing panel and interaction prompt backing','round passive node frames in ordinary notable locked available and allocated variants','thin passive tree connecting line segments and a selection ring','crafting panel border with recipe row separator','green and red translucent rectangular placement footprint indicators','button plates in normal hover pressed disabled states and general panel corners','small mouse pointer and crosshair reticle plus boss bar frame and restrained pause screen border accents']
for i,name in enumerate(ui,1):still('UI-'+str(i).zfill(2),'Game UI decorative component sheet: '+name+'. Each piece isolated with spacing, simple rectangular geometry, no words or numbers.',256,view='side')
(LIB/'queue.json').write_text(json.dumps(queue,indent=2))
print('Queued request units:',len(queue))
print('Character animation directions:',sum(t['endpoint']=='/animate-character' for t in queue))
